stages:
  - build
  - test
  - release
  - notify
  - deploy

include:
  - template: Security/SAST.gitlab-ci.yml
  - project: 'templates/ci'
    file: 'DockerInDockerTemplate.yml'

variables:
  VERSION: 1.0.{$CI_PIPELINE_ID}

build-frontend-image:
  stage: build
  image: docker:20.10.12-dind-rootless
  before_script:
    - until docker info; do sleep 1; done
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cd frontend
    - >
      docker build
      --build-arg VERSION=$VERSION
      --tag $CI_REGISTRY_IMAGE/project-frontend:$VERSION
      .
    - docker push $CI_REGISTRY_IMAGE/project-frontend:$VERSION

sonarqube-frontend-sast:
  stage: test
  image: sonarsource/sonar-scanner-cli:latest
  needs: []
  script:
    - cd frontend
    - >
      sonar-scanner -Dsonar.qualitygate.wait=true
      -Dsonar.projectKey="${SONAR_FRONTEND_PROJECT_KEY}"
      -Dsonar.sources=.
      -Dsonar.host.url="${SONAR_URL}"
      -Dsonar.login="${SONAR_FRONTEND_TOKEN}"
      -Dsonar.qualitygate.wait=false

eslint-sast:
  stage: test
  needs: []

gosec-sast:
  stage: test
  needs: []

nodejs-scan-sast:
  stage: test
  needs: []

semgrep-sast:
  stage: test
  needs: []

spotbugs-sast:
  stage: test
  rules:
    - when: never

release-frontend-image-latest:
  variables:
    GIT_STRATEGY: none
  image: docker:20.10.12-dind-rootless
  stage: release
  before_script:
    - until docker info; do sleep 1; done
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE/project-frontend:$VERSION
    - docker tag $CI_REGISTRY_IMAGE/project-frontend:$VERSION $CI_REGISTRY_IMAGE/project-frontend:latest
    - docker push $CI_REGISTRY_IMAGE/project-frontend:latest

release-frontend-helm-chart:
  stage: release
  image: alpine/helm:latest
  script:
    - cd infrastructure/helm
    - sed -i "s/{{TAG}}/$VERSION/" project-otus/charts/frontend/values.yaml
    - sed -i "s/{{VERSION}}/$VERSION/" project-otus/charts/frontend/Chart.yaml
    - helm package  project-otus/charts/frontend/ --version ${VERSION}
    - curl -u ${NEXUS_USER}:${NEXUS_PASSWORD} ${NEXUS_REPO_FRONTEND_HELM} --upload-file frontend-${VERSION}.tgz

telegram-notification-frontend:
  stage: notify
  script:
    - if [[ $CI_COMMIT_MESSAGE == *"send notification"* ]]; then curl -X POST -H 'Content-type:application/json' --data '{"chat_id":'${telegram_chat_id}', "text":"New version of the frontend helm chart has been released - '${VERSION}' and ready to deploy.\nYou can download it from the link - '${NEXUS_REPO_FRONTEND_HELM}backend-$VERSION'."}' https://api.telegram.org/${telegram_bot_token}/sendMessage; fi
  needs:
    - release-frontend-helm-chart

install-frontend-helm-chart:
  variables:
    GIT_STRATEGY: none
  stage: deploy
  image: alpine/helm:latest
  rules:
    - when: manual
  needs:
    - release-frontend-helm-chart
  before_script:
    - mkdir ~/.kube
    - cat ${KUBECONFIG} | base64 -d > ~/.kube/config
    - cat ${capem} | base64 -d > ~/.kube/ca.pem
    - export KUBECONFIG=~/.kube/config
  script:
    - helm repo add nexus ${NEXUS_REPO_FRONTEND_HELM} --username ${NEXUS_USER} --password ${NEXUS_PASSWORD}
    - helm repo update
    - helm upgrade frontend nexus/frontend -i --set image.tag=$VERSION  --atomic --namespace default
  after_script:
    - rm ~/.kube/config
