---
groups:
  - name: project-otus
    rules:
    - alert: InstanceDown
      expr: up{app="backend"} == 0
      for: 1m
      labels:
        severity: critical
        project: "project-otus"
        component: "Backend"
