image:
  repository: voovik59/project-backend
  pullPolicy: Always
  tag: ""
replicas: 2
revisionHistoryLimit: 15
strategy:
  type: RollingUpdate
rollingUpdate:
  maxUnavailable: 2
  maxSurge: 20%
service:
  port: 8081
imagePullSecrets:
  name: docker-config
  key: .dockerconfigjson
  value: "ewogICAgImF1dGhzIjogewogICAgICAgICJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOnsKICAgICAgICAgICAgInVzZXJuYW1lIjoia3ViX3lkdWFldiIsCiAgICAgICAgICAgICJwYXNzd29yZCI6IlVlcktENlg4blVIYnl3Z1R2ZnYzIiAgICAgICAgICAgCiAgICAgICAgfQogICAgfQp9Cg=="
  type: kubernetes.io/dockerconfigjson
